# Generated by Django 5.2.4 on 2025-08-24 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_tasks_belongs_to_same_user_of_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='tasks_belongs_to_same_user_of_group',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('task_group__isnull', True), ('user', models.F('task_group__user')), _connector='OR'), name='tasks_belongs_to_same_user_of_group'),
        ),
    ]
